package com.example.monitor.persistence;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.data.r2dbc.DataR2dbcTest;
import org.springframework.test.context.TestPropertySource;
import reactor.test.StepVerifier;

import java.time.Instant;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * 실제 R2DBC + H2(인메모리)로 schema.sql이 적용된 상태에서 리포지토리 쿼리를 검증한다.
 * 파일 DB(application.yml의 기본 설정)를 건드리지 않도록 인메모리 URL로 덮어쓴다.
 */
@DataR2dbcTest
@TestPropertySource(properties = "spring.r2dbc.url=r2dbc:h2:mem:///anomaly-monitor-test")
class AnomalyEventRepositoryTest {

    @Autowired
    private AnomalyEventRepository repository;

    @Test
    void findByDeviceIdOrderByDetectedAtDescReturnsOnlyThatDeviceNewestFirst() {
        Instant older = Instant.parse("2026-01-01T00:00:00Z");
        Instant newer = Instant.parse("2026-01-01T00:00:05Z");

        StepVerifier.create(
                repository.save(new AnomalyEventEntity("device-x", 90.0, 50.0, 5.0, 8.0, older))
                        .then(repository.save(new AnomalyEventEntity("device-x", 95.0, 50.0, 5.0, 9.0, newer)))
                        .then(repository.save(new AnomalyEventEntity("device-y", 10.0, 50.0, 5.0, -8.0, older)))
        ).expectNextCount(1).verifyComplete();

        StepVerifier.create(repository.findByDeviceIdOrderByDetectedAtDesc("device-x"))
                .assertNext(e -> assertThat(e.getDetectedAt()).isEqualTo(newer))
                .assertNext(e -> assertThat(e.getDetectedAt()).isEqualTo(older))
                .verifyComplete();
    }

    @Test
    void findAllByOrderByDetectedAtDescReturnsNewestFirst() {
        // 다른 테스트가 남긴 데이터와 순서가 섞이지 않도록 확실히 미래 시각을 쓴다.
        Instant older = Instant.parse("2099-01-01T00:00:00Z");
        Instant newer = Instant.parse("2099-01-01T00:00:10Z");

        StepVerifier.create(
                repository.save(new AnomalyEventEntity("device-order-a", 1.0, 0.0, 0.0, 0.0, older))
                        .then(repository.save(new AnomalyEventEntity("device-order-b", 2.0, 0.0, 0.0, 0.0, newer)))
        ).expectNextCount(1).verifyComplete();

        StepVerifier.create(repository.findAllByOrderByDetectedAtDesc().take(2))
                .assertNext(e -> assertThat(e.getDeviceId()).isEqualTo("device-order-b"))
                .assertNext(e -> assertThat(e.getDeviceId()).isEqualTo("device-order-a"))
                .verifyComplete();
    }

    @Test
    void savedEntityGetsAnAutoGeneratedId() {
        StepVerifier.create(repository.save(
                        new AnomalyEventEntity("device-id-check", 1.0, 0.0, 0.0, 0.0, Instant.now())))
                .assertNext(saved -> assertThat(saved.getId()).isNotNull())
                .verifyComplete();
    }
}
